apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
  labels:
    app: blog-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
    spec:
      containers:
        - name: blog-backend
          image: jinia91/blog-backend:1f484797318d19f371808399612aeefb9c59a533
          ports:
            - containerPort: 7777
          volumeMounts:
            - mountPath: /config/
              name: config-volume
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "optional:file:/config/application.yml"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7777
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7777
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
      volumes:
        - name: config-volume
          configMap:
            name: jiniaslog-config
---
apiVersion: v1
kind: Service
metadata:
  name: blog-backend-service
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  selector:
    app: blog-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7777
  type: ClusterIP
  sessionAffinity: ClientIP
  template:
    spec:
      containers:
        - image: jinia91/blog-backend:1f484797318d19f371808399612aeefb9c59a533
