apiVersion: v1
kind: Service
metadata:
  name: blog-backend-service
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
  labels:
    {{- include "blog-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "blog-backend.selectorLabels" . | nindent 4 }}
